[global]

[[bodies]]
name = "sun"
position = [0, 0, 0]
velocity = [0, 0, 0]
color = [255, 255, 0, 255]
radius = 1.3
mass = 2.7e6

[[bodies]]
name = "earth"
position = [7, 0, 0]
velocity = [0, 0.004, 0]
color = [0, 100, 200, 255]
radius = 0.8
mass = 4.5e5

# well, "moon"
[[bodies]]
name = "moon"
position = [8.5, 0, 0]
velocity = [0, -0.0007, 0]
color = [150, 200, 200, 255]
radius = 0.2
mass = 3e2

[[bodies]]
name = "weird-one"
position = [-7, 0, 0]
velocity = [0, 0, 0.005]
color = [255, 200, 100, 255]
radius = 0.5
mass = 2.5e5

# to compensate for system vertical momentum
# (there's still horizontal momentum, camera should be able to move lol)
[[bodies]]
name = "weird-one-twin"
position = [0, 7, 0]
velocity = [0, 0, -0.005]
color = [255, 100, 200, 255]
radius = 0.5
mass = 2.5e5

[[directional_lights]]
intensity = 1.0
color = [255, 255, 255, 255]
position = [0, -0.5, -0.5]

[[directional_lights]]
intensity = 1.0
color = [255, 255, 255, 255]
position = [0, 0.5, 0.5]

[cheats]
time_mult = 0.3
